name: tests

on:
    push:
        branches:
            - master

jobs:
    test:
        name: run tests
        runs-on: ubuntu-20.04

        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: install node
              uses: actions/setup-node@v4
              with:
                node-version-file: '.nvmrc'
            - name: node info
              run: |
                node --version
                npm --version
            - name: install dependencies
              run: npm install
            - name: run the tests
              run: AOC_YEAR=2023 npm test
